# Alembic migration env configuration
# This file is generated by `alembic init`

import logging
from logging.config import fileConfig

from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context

# this is the Alembic Config object, which provides
# the values of various Alembic directives to Python code
# by means of the `Config.variables` dictionary as well as
# individual arguments given to the env.py command
# line.

config = context.config

# Interpret the config file for Python logging.
# This code creates loggers per the config file.
# The fileConfig() call below takes care of setting
# things up so that we use UTC for all timestamps
# from the Python side, as a well as have the
# Logging configuration set up as expected by the
# Python application code using SQLAlchemy
# (if they use the standard Python logging module
# through the standard logging.config module).
if config.config_file_name is not None:
    fileConfig(config.config_file_name)
logger = logging.getLogger('alembic.env')

# add your model's MetaData object here
# for 'autogenerate' support
# from myapp import mymodel
# target_metadata = mymodel.Base.metadata
target_metadata = None

# other values from the config, defined by the [alembic]
# section and passed through the `context.configure()`
# call, are available via the `config.get_section(config.config_file_ini_section)` dictionary
# for use within custom 'env.py' files, that example illustrates doing this

def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode."""
    configuration = config.get_section(config.config_ini_section)
    configuration["sqlalchemy.url"] = os.getenv("DATABASE_URL")

    connectable = engine_from_config(
        configuration, prefix="sqlalchemy.", poolclass=pool.StaticPool
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()

def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""
    import os
    from sqlalchemy import engine_from_config, pool

    configuration = config.get_section(config.config_ini_section)
    configuration["sqlalchemy.url"] = os.getenv(
        "DATABASE_URL",
        "postgresql://brain_user:brain_password@localhost:5432/project_brain"
    )

    connectable = engine_from_config(
        configuration, prefix="sqlalchemy.", poolclass=pool.NullPool
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
